services:
  web:
    build:
      context: .
      target: develop
      args:
        VITE_PB_URL: 'http://localhost:8090/'
        VITE_LLMS_URL: 'http://localhost:8000/llms/'
    image: llms-micro-blog-web:latest
    ports:
      - '5173:5173'

    develop:
      watch:
        - action: sync
          path: .
          target: /home/bun/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
